packages:
  - apps/*

allowBuilds:
  esbuild: true
  unrs-resolver: true
  vue-demi: true

catalog:
  '@iconify-json/lucide': ^1.2.117
  '@iconify-json/simple-icons': ^1.2.90
  '@nuxt/ui': ^4.10.0
  '@nuxt/eslint': ^1.16.0
  '@nuxt/test-utils': ^4.0.3
  nuxt: ^4.4.8
  tailwindcss: ^4.3.2
  eslint: ^10.7.0
  happy-dom: ^20.11.0
  typescript: ^6.0.3
  vitest: ^4.1.10
  vue-tsc: ^3.3.7
